spring:
  application:
    name: campus-coffee
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false
logging:
  file:
    name: campus-coffee.log
server:
  error:
    whitelabel:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
server:
  error:
    include-message: always
    include-binding-errors: always
springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
